const vocabSets = {
    // === ชุดที่ 1: Marketing & Sales ===
    set1: [
        { word: "Advertise", read: "แอด-เวอ-ไทซ", pos: "v.", meaning: "โฆษณา", example: "The company decided to advertise its new product on social media." },
        { word: "Brand", read: "แบรนด์", pos: "n.", meaning: "ตราสินค้า", example: "Apple is a globally recognized brand." },
        { word: "Campaign", read: "แคม-เพน", pos: "n.", meaning: "แคมเปญ, การรณรงค์", example: "The marketing campaign increased sales by twenty percent." },
        { word: "Consumer", read: "คอน-ซู-เมอร์", pos: "n.", meaning: "ผู้บริโภค", example: "We need to understand consumer behavior to improve our product." },
        { word: "Demand", read: "ดิ-มานด์", pos: "n./v.", meaning: "ความต้องการ", example: "There is a high demand for electric vehicles this year." },
        { word: "Promote", read: "โพร-โมท", pos: "v.", meaning: "ส่งเสริม, เลื่อนตำแหน่ง", example: "They use discounts to promote their new store." },
        { word: "Strategy", read: "สแตร-เท-จี", pos: "n.", meaning: "กลยุทธ์", example: "The manager explained the business strategy to the team." },
        { word: "Target", read: "ทาร์-เก็ต", pos: "n./v.", meaning: "เป้าหมาย", example: "Our primary target audience is college students." },
        { word: "Trend", read: "เทรนด์", pos: "n.", meaning: "แนวโน้ม", example: "Online shopping is a growing trend worldwide." },
        { word: "Sponsor", read: "สปอน-เซอร์", pos: "n./v.", meaning: "ผู้สนับสนุน", example: "The big bank is the main sponsor of the event." },
        { word: "Brochure", read: "โบร-ชัวร์", pos: "n.", meaning: "แผ่นพับ", example: "Please read this brochure for more details about our tour." },
        { word: "Publicity", read: "พับ-ลิส-ซิ-ที", pos: "n.", meaning: "การประชาสัมพันธ์", example: "The movie received a lot of positive publicity." },
        { word: "Survey", read: "เซอร์-เวย์", pos: "n./v.", meaning: "การสำรวจ", example: "We conducted a survey to get customer feedback." },
        { word: "Feedback", read: "ฟีด-แบ็ก", pos: "n.", meaning: "ผลตอบรับ", example: "Positive feedback from users encourages our developers." },
        { word: "Launch", read: "ลอนช์", pos: "v./n.", meaning: "เปิดตัวสินค้า", example: "The tech giant plans to launch a new smartphone next month." },
        { word: "Logo", read: "โล-โก้", pos: "n.", meaning: "สัญลักษณ์", example: "The company logo is printed on every box." },
        { word: "Slogan", read: "สโล-แกน", pos: "n.", meaning: "สโลแกน", example: "Just Do It is a famous slogan of Nike." },
        { word: "Competitor", read: "คอม-เพ็ต-ติ-เทอร์", pos: "n.", meaning: "คู่แข่ง", example: "We must monitor what our competitor is doing." },
        { word: "Market Share", read: "มาร์-เก็ต แชร์", pos: "n.", meaning: "ส่วนแบ่งการตลาด", example: "Our company holds the largest market share in Asia." },
        { word: "Niche", read: "นิช", pos: "adj./n.", meaning: "กลุ่มตลาดเฉพาะ", example: "Organic pet food is a niche market." },
        { word: "Segment", read: "เซก-เม้นท์", pos: "n.", meaning: "ส่วนตลาด", example: "The luxury car segment is growing rapidly." },
        { word: "Loyalty", read: "ลอย-อัล-ที", pos: "n.", meaning: "ความจงรักภักดี", example: "The reward program helps build customer loyalty." },
        { word: "Endorse", read: "เอ็น-ดอร์ส", pos: "v.", meaning: "รับรอง, เป็นพรีเซนเตอร์", example: "Famous athletes usually endorse sportswear brands." },
        { word: "Merchandise", read: "เมอร์-ชัน-ไดซ์", pos: "n.", meaning: "สินค้า", example: "Official merchandise is available at the concert venue." },
        { word: "Retail", read: "รี-เทล", pos: "n./adj.", meaning: "การขายปลีก", example: "The retail price of this item is fifty dollars." },
        { word: "Wholesale", read: "โฮล-เซล", pos: "n./adj.", meaning: "การขายส่ง", example: "Buying in bulk allows you to get the wholesale price." },
        { word: "Discount", read: "ดิส-เคาท์", pos: "n./v.", meaning: "ส่วนลด", example: "They offer a ten percent discount for students." },
        { word: "Attraction", read: "อะ-แทร็ก-ชัน", pos: "n.", meaning: "การดึงดูด", example: "The low price is the main attraction for buyers." },
        { word: "Display", read: "ดิส-เพลย์", pos: "v./n.", meaning: "การจัดแสดง", example: "New arrivals are on display near the entrance." },
        { word: "Persuade", read: "เพอร์-สเวด", pos: "v.", meaning: "โน้มน้าว", example: "The salesman tried to persuade me to buy the insurance." }
    ],

    // === ชุดที่ 2: Finance & Accounting ===
    set2: [
        { word: "Budget", read: "บัด-เจ็ต", pos: "n./v.", meaning: "งบประมาณ", example: "We must strictly follow the annual budget." },
        { word: "Invoice", read: "อิน-วอยซ์", pos: "n.", meaning: "ใบแจ้งหนี้", example: "Please send the invoice to the accounting department." },
        { word: "Revenue", read: "เรฟ-เว-นิว", pos: "n.", meaning: "รายได้", example: "Company revenue increased significantly last quarter." },
        { word: "Expense", read: "เอ็กซ์-เพนส์", pos: "n.", meaning: "ค่าใช้จ่าย", example: "Travel expenses will be reimbursed by the office." },
        { word: "Audit", read: "ออ-ดิต", pos: "n./v.", meaning: "การตรวจสอบบัญชี", example: "The external auditors will examine our financial books next week." },
        { word: "Profit", read: "พรอ-ฟิต", pos: "n.", meaning: "กำไร", example: "The business yielded a high profit this year." },
        { word: "Deficit", read: "เดฟ-ฟิ-สิต", pos: "n.", meaning: "การขาดดุล", example: "The federal government is facing a huge budget deficit." },
        { word: "Asset", read: "แอส-เซ็ท", pos: "n.", meaning: "สินทรัพย์", example: "Real estate is considered a valuable long-term asset." },
        { word: "Liability", read: "ไล-อะ-บิ-ลิ-ที", pos: "n.", meaning: "หนี้สิน", example: "The company's total liabilities outweigh its assets." },
        { word: "Capital", read: "แคพ-พิ-ทอล", pos: "n.", meaning: "เงินทุน", example: "We need more capital to expand our factory." },
        { word: "Tax", read: "แท็กซ์", pos: "n./v.", meaning: "ภาษี", example: "Citizens must pay income tax before the deadline." },
        { word: "Refund", read: "รี-ฟันด์", pos: "n./v.", meaning: "เงินคืน", example: "If the product is broken, you can claim a full refund." },
        { word: "Currency", read: "เคอร์-เรน-ซี", pos: "n.", meaning: "สกุลเงิน", example: "The US Dollar is a globally traded currency." },
        { word: "Invest", read: "อิน-เวสต์", pos: "v.", meaning: "ลงทุน", example: "It is wise to invest some money in stocks." },
        { word: "Transaction", read: "ทรัน-แซก-ชัน", pos: "n.", meaning: "ธุรกรรม", example: "The online transaction was completed successfully." },
        { word: "Accountant", read: "อะ-เคาน์-แทนต์", pos: "n.", meaning: "นักบัญชี", example: "Our accountant handles all tax forms." },
        { word: "Balance", read: "บาล-แลนซ์", pos: "n./v.", meaning: "ยอดคงเหลือ", example: "You can check your bank account balance at any ATM." },
        { word: "Credit", read: "เคร-ดิต", pos: "n./v.", meaning: "สินเชื่อ", example: "The bank granted him a line of credit." },
        { word: "Debt", read: "เด็ท", pos: "n.", meaning: "หนี้สิน", example: "He is working hard to pay off his student debt." },
        { word: "Interest", read: "อิน-เทรสท์", pos: "n.", meaning: "ดอกเบี้ย", example: "The savings account offers a fixed interest rate." },
        { word: "Portfolio", read: "พอร์ต-โฟ-ลิ-โอ", pos: "n.", meaning: "แฟ้มผลงานการลงทุน", example: "Diversifying your portfolio reduces financial risk." },
        { word: "Bankruptcy", read: "แบงค์-รัพ-ซี", pos: "n.", meaning: "การล้มละลาย", example: "The retail chain filed for bankruptcy last Tuesday." },
        { word: "Dividend", read: "ดิ-วิ-เดนด์", pos: "n.", meaning: "เงินปันผล", example: "Shareholders will receive their dividend payments tomorrow." },
        { word: "Ledger", read: "เลด-เจอร์", pos: "n.", meaning: "สมุดบัญชีแยกประเภท", example: "All financial records are copied into the main ledger." },
        { word: "Payment", read: "เพย์-เม้นท์", pos: "n.", meaning: "การชำระเงิน", example: "The payment is due within thirty days." },
        { word: "Statement", read: "สเตท-เม้นท์", pos: "n.", meaning: "ใบแจ้งยอดบัญชี", example: "I receive a monthly bank statement via email." },
        { word: "Fund", read: "ฟันด์", pos: "n./v.", meaning: "กองทุน", example: "The government raised funds to build a new school." },
        { word: "Estimate", read: "เอส-ติ-เมท", pos: "v./n.", meaning: "ประมาณการ", example: "The engineer gave a cost estimate for the repairs." },
        { word: "Forecast", read: "ฟอร์-แคสต์", pos: "n./v.", meaning: "พยากรณ์ล่วงหน้า", example: "Experts forecast steady financial economic growth." },
        { word: "Yield", read: "ยีลด์", pos: "n./v.", meaning: "ผลตอบแทน", example: "High-risk bonds usually offer a higher yield." }
    ],

    // === ชุดที่ 3: Corporate Management ===
    set3: [
        { word: "Executive", read: "เอ็ก-เซ-คิว-ทิฝ", pos: "n./adj.", meaning: "ผู้บริหาร", example: "The chief executive officer made the final decision." },
        { word: "Merger", read: "เมอร์-เจอร์", pos: "n.", meaning: "การควบรวมกิจการ", example: "The merger of the two airlines created a giant company." },
        { word: "Acquire", read: "อะ-ควาย-เออร์", pos: "v.", meaning: "เข้าซื้อกิจการ, ได้รับ", example: "Our company plans to acquire a local software startup." },
        { word: "Board", read: "บอร์ด", pos: "n.", meaning: "คณะกรรมการ", example: "The board of directors approved the new policy." },
        { word: "Policy", read: "พอล-ลิ-ซี", pos: "n.", meaning: "นโยบาย", example: "The company has a strict policy against smoking." },
        { word: "Structure", read: "สตรัค-เจอร์", pos: "n./v.", meaning: "โครงสร้าง", example: "The corporate structure has three management layers." },
        { word: "Supervise", read: "ซู-เพอร์-ไวซ์", pos: "v.", meaning: "ควบคุมดูแล", example: "The manager will supervise the new interns." },
        { word: "Coordinate", read: "โค-ออร์-ดิ-เนท", pos: "v.", meaning: "ประสานงาน", example: "We need to coordinate with the marketing team." },
        { word: "Regulate", read: "เร-กู-เลท", pos: "v.", meaning: "ควบคุม, ออกกฎเกณฑ์", example: "New laws regulate safety standards in factories." },
        { word: "Decision", read: "ดิ-ซิ-ชัน", pos: "n.", meaning: "การตัดสินใจ", example: "It was a difficult decision to close the branch." },
        { word: "Implement", read: "อิม-พลี-เมนท์", pos: "v.", meaning: "นำไปปฏิบัติจริง", example: "We will implement the new system next Monday." },
        { word: "Negotiate", read: "เน-โก-เชีย-เอท", pos: "v.", meaning: "เจรจาต่อรอง", example: "The union is meeting to negotiate a higher salary." },
        { word: "Partnership", read: "พาร์ท-เนอร์-ชิพ", pos: "n.", meaning: "หุ้นส่วน, พันธมิตร", example: "The two tech companies formed a long-term partnership." },
        { word: "Venture", read: "เวน-เจอร์", pos: "n./v.", meaning: "การลงทุนเสี่ยงโชค", example: "Their joint venture in Japan proved highly profitable." },
        { word: "Expansion", read: "เอ็ก-แพน-ชัน", pos: "n.", meaning: "การขยายตัว", example: "The business expansion created fifty new jobs." },
        { word: "Subsidiary", read: "ซับ-สิ-ดิ-เอ-รี", pos: "n.", meaning: "บริษัทในเครือ", example: "The Japanese company has a subsidiary in Thailand." },
        { word: "Vision", read: "วิ-ชัน", pos: "n.", meaning: "วิสัยทัศน์", example: "The founder shared his vision for the future." },
        { word: "Objective", read: "ออบ-เจก-ทิฝ", pos: "n.", meaning: "วัตถุประสงค์", example: "Our main objective is to reduce production costs." },
        { word: "Mission", read: "มิ-ชัน", pos: "n.", meaning: "ภารกิจ", example: "The company's mission is to provide clean energy." },
        { word: "Oversee", read: "โอ-เวอร์-ซี", pos: "v.", meaning: "คุมงาน, ตรวจตรา", example: "A vice president was appointed to oversee the project." },
        { word: "Leadership", read: "ลีด-เดอร์-ชิพ", pos: "n.", meaning: "ภาวะผู้นำ", example: "Under her leadership, the organization grew rapidly." },
        { word: "Restructure", read: "รี-สตรัค-เจอร์", pos: "v.", meaning: "ปรับโครงสร้างใหม่", example: "The company must restructure to avoid economic loss." },
        { word: "Direct", read: "ได-เร็กต์", pos: "v./adj.", meaning: "สั่งการ, โดยตรง", example: "The supervisor will direct you to your assigned desk." },
        { word: "Guidelines", read: "ไกด์-ไลน์ซ", pos: "n.", meaning: "แนวทางปฏิบัติ", example: "Employees must strictly follow the safety guidelines." },
        { word: "Committee", read: "คอม-มิ-ตี", pos: "n.", meaning: "คณะกรรมการ", example: "The planning committee will meet at noon." },
        { word: "Evaluate", read: "อิ-แวล-ลู-เอท", pos: "v.", meaning: "ประเมินผล", example: "Managers evaluate employee performance every December." },
        { word: "Efficiency", read: "อิ-ฟิ-เชียน-ซี", pos: "n.", meaning: "ประสิทธิภาพ", example: "The new machinery improved manufacturing efficiency." },
        { word: "Compliance", read: "คอม-พลาย-แอนส์", pos: "n.", meaning: "การปฏิบัติตามกฎ", example: "The laboratory acts in full compliance with safety laws." },
        { word: "Monopoly", read: "โม-โน-โพ-ลี", pos: "n.", meaning: "การผูกขาด", example: "The government regulated the firm to prevent a monopoly." },
        { word: "Authority", read: "ออ-ธอ-ริ-ที", pos: "n.", meaning: "อำนาจหน้าที่", example: "The manager has the authority to approve travel funds." }
    ],

    // === ชุดที่ 4: Human Resources ===
    set4: [
        { word: "Recruit", read: "รี-ครูท", pos: "v./n.", meaning: "สรรหาบุคลากร", example: "We need to recruit a qualified web developer." },
        { word: "Candidate", read: "แคน-ดิ-เดท", pos: "n.", meaning: "ผู้สมัคร", example: "She is a strong candidate for the sales job." },
        { word: "Resume", read: "เร-ซู-เม่", pos: "n.", meaning: "ประวัติย่อ", example: "Please attach your current resume to the email." },
        { word: "Interview", read: "อิน-เทอร์-วิว", pos: "n./v.", meaning: "การสัมภาษณ์", example: "The human resources manager conducted the interview." },
        { word: "Hire", read: "ไฮ-เออร์", pos: "v.", meaning: "จ้างงาน", example: "The restaurant owner decided to hire extra waiters." },
        { word: "Benefit", read: "เบน-เน-ฟิต", pos: "n./v.", meaning: "สวัสดิการ, ประโยชน์", example: "Health insurance is a standard employee benefit." },
        { word: "Salary", read: "แซล-ละ-รี", pos: "n.", meaning: "เงินเดือน", example: "He negotiated a higher starting salary." },
        { word: "Payroll", read: "เพย์-โรล", pos: "n.", meaning: "บัญชีเงินเดือน", example: "The payroll department processes salaries on Fridays." },
        { word: "Terminate", read: "เทอร์-มิ-เนท", pos: "v.", meaning: "เลิกจ้าง, สิ้นสุด", example: "The contract will terminate at the end of the year." },
        { word: "Resign", read: "รี-ซายน์", pos: "v.", meaning: "ลาออก", example: "The sales director chose to resign from his post." },
        { word: "Retire", read: "รี-ไทร์", pos: "v.", meaning: "เกษียณอายุ", example: "Most employees retire when they reach sixty." },
        { word: "Qualification", read: "ควอ-ลิ-ฟิ-เค-ชัน", pos: "n.", meaning: "คุณสมบัติ", example: "A master's degree is a necessary qualification for this role." },
        { word: "Applicant", read: "แอพ-พลิ-แคนท์", pos: "n.", meaning: "ผู้สมัครงาน", example: "There were over a hundred applicants for the internship." },
        { word: "Appraisal", read: "อะ-เพร-ซอล", pos: "n.", meaning: "การประเมินค่า", example: "Annual performance appraisals help determine raises." },
        { word: "Bonus", read: "โบนัส", pos: "n.", meaning: "เงินโบนัสพิเศษ", example: "Employees received a generous cash bonus for Christmas." },
        { word: "Contract", read: "คอน-แทร็กต์", pos: "n./v.", meaning: "สัญญา", example: "Be sure to read the employment contract before signing." },
        { word: "Vacancy", read: "เว-แคน-ซี", pos: "n.", meaning: "ตำแหน่งงานว่าง", example: "The company has a sudden vacancy in marketing." },
        { word: "Employee", read: "เอ็ม-พลอย-อี", pos: "n.", meaning: "ลูกจ้าง, พนักงาน", example: "Every employee must wear an identification badge." },
        { word: "Employer", read: "เอ็ม-พลอย-เออร์", pos: "n.", meaning: "นายจ้าง", example: "Google is known as a top employer worldwide." },
        { word: "Intern", read: "อิน-เทิร์น", pos: "n.", meaning: "เด็กฝึกงาน", example: "The intern assisted with filing office paperwork." },
        { word: "Dismiss", read: "ดิ-มิส", pos: "v.", meaning: "ไล่ออก", example: "The board voted to dismiss the careless worker." },
        { word: "Insurance", read: "อิน-ชู-รันส์", pos: "n.", meaning: "การประกันภัย", example: "The company covers comprehensive dental insurance." },
        { word: "Compensation", read: "คอม-เพน-เซ-ชัน", pos: "n.", meaning: "ค่าตอบแทน, ค่าสินไหม", example: "Workers receive fair compensation for injuries." },
        { word: "Overtime", read: "โอ-เวอร์-ไทม์", pos: "n./adv.", meaning: "การทำงานล่วงเวลา", example: "Staff are paid double for working overtime." },
        { word: "Absent", read: "แอบ-เซนต์", pos: "adj.", meaning: "ขาดงาน, ไม่มา", example: "He was absent from the meeting due to illness." },
        { word: "Personnel", read: "เพอร์-ซัน-เนล", pos: "n.", meaning: "บุคลากร", example: "All queries should be directed to personnel." },
        { word: "Retain", read: "รี-เทน", pos: "v.", meaning: "รักษาไว้, จ้างไว้", example: "We offer perks to retain talented executives." },
        { word: "Maternity", read: "มะ-เทอร์-นิ-ที", pos: "n./adj.", meaning: "การเป็นมารดา, ลาคลอด", example: "She is currently taking a three-month maternity leave." },
        { word: "Pension", read: "เพน-ชัน", pos: "n.", meaning: "เงินบำนาญ", example: "He lives comfortably on his monthly government pension." },
        { word: "Colleague", read: "คอล-ลีก", pos: "n.", meaning: "เพื่อนร่วมงาน", example: "My colleague helped me finish the financial draft." }
    ],

    // === ชุดที่ 5: Office Administration ===
    set5: [
        { word: "Agenda", read: "อะ-เจน-ด้า", pos: "n.", meaning: "วาระการประชุม", example: "The first item on the agenda is the financial report." },
        { word: "Minutes", read: "มิน-นิทส์", pos: "n.", meaning: "บันทึกการประชุม", example: "The secretary took detailed minutes during the staff meeting." },
        { word: "Schedule", read: "สเกด-จูล", pos: "n./v.", meaning: "ตารางเวลา", example: "Our project is running ahead of schedule." },
        { word: "Memo", read: "เม-โม่", pos: "n.", meaning: "บันทึกข้อความภายใน", example: "The director sent a memo regarding the office dress code." },
        { word: "File", read: "ไฟล์", pos: "n./v.", meaning: "แฟ้มข้อมูล", example: "Please organize these files in alphabetical order." },
        { word: "Document", read: "ด็อค-คิว-เมนท์", pos: "n.", meaning: "เอกสาร", example: "Sign your name at the bottom of the document." },
        { word: "Archive", read: "อาร์-คายฝ", pos: "n./v.", meaning: "คลังเอกสารเก่า", example: "Old records are kept safely in the digital archive." },
        { word: "Equipment", read: "อิ-ควิป-เมนท์", pos: "n.", meaning: "อุปกรณ์", example: "The office upgraded its printing equipment." },
        { word: "Supply", read: "ซัพ-พลาย", pos: "n./v.", meaning: "วัสดุอุปกรณ์, จัดหา", example: "We need to order more stationery supplies." },
        { word: "Correspondence", read: "คอร์-เรส-พอน-เดนส์", pos: "n.", meaning: "จดหมายโต้ตอบ", example: "The clerk handles all incoming and outgoing correspondence." },
        { word: "Stationery", read: "สเต-ชัน-เนอ-รี", pos: "n.", meaning: "เครื่องเขียน", example: "Envelopes and pens are available in the stationery cupboard." },
        { word: "Arrange", read: "อะ-เรนจ์", pos: "v.", meaning: "จัดเตรียม, จัดระเบียบ", example: "The assistant will arrange a meeting with the client." },
        { word: "Confirm", read: "คอน-เฟิร์ม", pos: "v.", meaning: "ยืนยัน", example: "Please call the hotel to confirm our reservation." },
        { word: "Postpone", read: "โพสต์-โพน", pos: "v.", meaning: "เลื่อนเวลาออกไป", example: "They decided to postpone the conference until next month." },
        { word: "Cancel", read: "แคน-เซิล", pos: "v.", meaning: "ยกเลิก", example: "Bad weather forced them to cancel the outdoor event." },
        { word: "Forward", read: "ฟอร์-เวิร์ด", pos: "v.", meaning: "ส่งต่อ (อีเมล/จดหมาย)", example: "Could you please forward that email to the manager?" },
        { word: "Organize", read: "ออร์-กะ-ไนซ์", pos: "v.", meaning: "จัดระบบ, จัดตั้ง", example: "We need a temporary team to organize the annual seminar." },
        { word: "Inventory", read: "อิน-เวน-ทอ-รี", pos: "n.", meaning: "สินค้าคงคลัง, สินทรัพย์ที่มี", example: "The store closes early on Sundays for inventory checking." },
        { word: "Procedure", read: "พรอ-ซี-เจอร์", pos: "n.", meaning: "ขั้นตอนการดำเนินงาน", example: "What is the standard procedure for requesting leave?" },
        { word: "Update", read: "อัป-เดท", pos: "v./n.", meaning: "ข้อมูลล่าสุด, ปรับปรุง", example: "The manager asked for an update on the sales progress." },
        { word: "Brief", read: "บรีฟ", pos: "v./adj.", meaning: "สรุปย่อ", example: "The boss gave a brief overview of the contract." },
        { word: "Co-worker", read: "โค-เวิร์ก-เกอร์", pos: "n.", meaning: "เพื่อนร่วมงาน", example: "My co-worker invited me to lunch today." },
        { word: "Maintain", read: "เมน-เทน", pos: "v.", meaning: "บำรุงรักษา, คงไว้", example: "The technician arrives monthly to maintain the copier." },
        { word: "Resource", read: "รี-ซอร์ส", pos: "n.", meaning: "ทรัพยากร", example: "The internet is a valuable resource for research." },
        { word: "Network", read: "เน็ต-เวิร์ก", pos: "n./v.", meaning: "เครือข่าย", example: "The office computer network is secured by a firewall." },
        { word: "Calendar", read: "แคล-เลน-ดาร์", pos: "n.", meaning: "ปฏิทิน", example: "Mark the workshop date on your desk calendar." },
        { word: "Administer", read: "แอด-มิ-นิส-เทอร์", pos: "v.", meaning: "จัดการ, บริหาร", example: "The director was chosen to administer the charity fund." },
        { word: "Cabinet", read: "แคบ-บิ-เน็ท", pos: "n.", meaning: "ตู้เก็บเอกสาร/ตู้โชว์", example: "Keep confidential contracts in the locked filing cabinet." },
        { word: "Extension", read: "เอ็กซ์-เทน-ชัน", pos: "n.", meaning: "เบอร์โทรศัพท์ภายใน, การต่อเวลา", example: "To reach marketing, dial extension number four-two." },
        { word: "Stapler", read: "สเต-เพลอร์", pos: "n.", meaning: "ที่เย็บกระดาษ", example: "I need a heavy-duty stapler to bind these reports." }
    ],

    // === ชุดที่ 6: Purchasing & Logistics ===
    set6: [
        { word: "Purchase", read: "เพอร์-เชส", pos: "v./n.", meaning: "ซื้อ, การจัดซื้อ", example: "You can purchase tickets directly online." },
        { word: "Order", read: "ออร์-เดอร์", pos: "n./v.", meaning: "คำสั่งซื้อ", example: "The supplier is preparing our bulk order." },
        { word: "Supplier", read: "ซัพ-พลาย-เออร์", pos: "n.", meaning: "ผู้จัดหาสินค้าให้", example: "We get our raw materials from a local supplier." },
        { word: "Vendor", read: "เวน-เดอร์", pos: "n.", meaning: "ผู้ขาย, พ่อค้า", example: "The street food vendor opens at five in the evening." },
        { word: "Ship", read: "ชิป", pos: "v.", meaning: "ขนส่งสินค้า", example: "The warehouse will ship your order tomorrow morning." },
        { word: "Delivery", read: "ดิ-ลิ-เวอ-รี", pos: "n.", meaning: "การจัดส่ง", example: "Free delivery is offered for purchases over forty dollars." },
        { word: "Cargo", read: "คาร์-โก้", pos: "n.", meaning: "สินค้าที่บรรทุก", example: "The cargo ship arrived safely at the deep harbor." },
        { word: "Freight", read: "เฟรท", pos: "n.", meaning: "ค่าระวาง, การขนส่งสินค้า", example: "Air freight is faster but more expensive than sea transport." },
        { word: "Warehouse", read: "แวร์-เฮาส์", pos: "n.", meaning: "คลังสินค้า", example: "The extra inventory is stored in the main warehouse." },
        { word: "Stock", read: "สต็อก", pos: "n./v.", meaning: "สินค้าในคลัง", example: "The popular shoe model is currently out of stock." },
        { word: "Track", read: "แทร็ก", pos: "v.", meaning: "ติดตามเส้นทาง", example: "Customers can track their parcels using a mobile app." },
        { word: "Transport", read: "ทรัน-สปอร์ต", pos: "v./n.", meaning: "การขนส่ง", example: "Public transport helps reduce downtown traffic." },
        { word: "Distribute", read: "ดิ-สทริ-บิวท์", pos: "v.", meaning: "แจกจ่าย, กระจายสินค้า", example: "The logistics center will distribute boxes to local stores." },
        { word: "Logistics", read: "โล-จิส-ติกส์", pos: "n.", meaning: "ระบบการจัดการขนส่ง", example: "He studied logistics and supply chain management." },
        { word: "Carrier", read: "แคร์-ริ-เออร์", pos: "n.", meaning: "บริษัทผู้ให้บริการขนส่ง", example: "DHL is a major international cargo carrier." },
        { word: "Import", read: "อิม-พอร์ต", pos: "v./n.", meaning: "นำเข้าสินค้า", example: "Thailand imports petroleum from the Middle East." },
        { word: "Export", read: "เอ็กซ์-พอร์ต", pos: "v./n.", meaning: "ส่งออกสินค้า", example: "Rice is a primary agricultural export of the country." },
        { word: "Transit", read: "ทรัน-สิท", pos: "n.", meaning: "การเดินทางผ่าน", example: "The goods were damaged while in transit." },
        { word: "Dispatch", read: "ดิส-แพทช์", pos: "v./n.", meaning: "ส่งสินค้าออกไป", example: "The courier will dispatch the package within an hour." },
        { word: "Bulk", read: "บัลค์", pos: "n./adj.", meaning: "จำนวนมาก, ขายส่ง", example: "Buying in bulk reduces individual packaging waste." },
        { word: "Receipt", read: "รี-ซีท", pos: "n.", meaning: "ใบเสร็จรับเงิน", example: "Please keep your receipt as proof of payment." },
        { word: "Package", read: "แพ็ค-เกจ", pos: "n./v.", meaning: "พัสดุ, หีบห่อ", example: "The mailman delivered a heavy package to my door." },
        { word: "Shipment", read: "ชิป-เม้นท์", pos: "n.", meaning: "การส่งสินค้า", example: "The next shipment of microchips arrives next Friday." },
        { word: "Customs", read: "คัส-ตัมส์", pos: "n.", meaning: "ศุลกากร", example: "Passengers must pass through customs at the airport." },
        { word: "Delay", read: "ดิ-เลย์", pos: "n./v.", meaning: "ความล่าช้า", example: "Heavy snow caused a long delay in train services." },
        { word: "Storage", read: "สโต-เรจ", pos: "n.", meaning: "การจัดเก็บสินค้า", example: "Cold storage is required for keeping meat fresh." },
        { word: "Fleet", read: "ฟลีท", pos: "n.", meaning: "กลุ่มยานพาหนะ", example: "The logistics firm owns a large fleet of delivery trucks." },
        { word: "Procure", read: "พรอ-คิว-เออร์", pos: "v.", meaning: "จัดซื้อจัดหามา", example: "The administrative assistant must procure office electronics." },
        { word: "Consignment", read: "คอน-ไซน์-เม้นท์", pos: "n.", meaning: "สินค้าที่ส่งฝากขาย", example: "The fresh clothing consignment was delivered safely yesterday." },
        { word: "Lading", read: "เล-ดิ้ง", pos: "n.", meaning: "การบรรทุกสินค้า", example: "The bill of lading lists all items loaded onto the ship." }
    ],

    // === ชุดที่ 7: Manufacturing ===
    set7: [
        { word: "Factory", read: "แฟค-ทอ-รี", pos: "n.", meaning: "โรงงาน", example: "The car factory employs over two thousand workers." },
        { word: "Produce", read: "พรอ-ดิวซ์", pos: "v.", meaning: "ผลิต", example: "They produce high-quality organic cotton shirts." },
        { word: "Assembly", read: "อะ-เซม-บลี", pos: "n.", meaning: "สายการประกอบชิ้นส่วน", example: "Robots are used on the automated assembly line." },
        { word: "Component", read: "คอม-โพ-เนนท์", pos: "n.", meaning: "ส่วนประกอบชิ้นส่วน", example: "The electronic component was manufactured in Taiwan." },
        { word: "Material", read: "มะ-ที-เรียล", pos: "n.", meaning: "วัสดุ", example: "Wood is the primary material used to build this chair." },
        { word: "Defect", read: "ดี-เฟกต์", pos: "n.", meaning: "ตำหนิ, ข้อบกพร่อง", example: "Inspectors check the glass bottles for any slight defects." },
        { word: "Inspect", read: "อิน-สเปกต์", pos: "v.", meaning: "ตรวจสอบอย่างละเอียด", example: "Engineers arrive weekly to inspect the bridge structure." },
        { word: "Machinery", read: "มะ-ชีน-เนอ-รี", pos: "n.", meaning: "เครื่องจักรกล", example: "The heavy manufacturing machinery requires skilled operators." },
        { word: "Output", read: "เอาต์-พุต", pos: "n.", meaning: "ผลผลิตที่ได้", example: "The factory's daily output increased by ten percent." },
        { word: "Automation", read: "ออ-โต-เม-ชัน", pos: "n.", meaning: "ระบบอัตโนมัติ", example: "Factory automation reduces human error in packing." },
        { word: "Facility", read: "ฟะ-ซิล-ลิ-ที", pos: "n.", meaning: "โรงงานหรือสิ่งอำนวยความสะดวก", example: "The new processing facility will open next year." },
        { word: "Standard", read: "สแตน-ดาร์ด", pos: "n./adj.", meaning: "มาตรฐาน", example: "All products must meet international safety standards." },
        { word: "Plant", read: "พลานท์", pos: "n.", meaning: "โรงงานอุตสาหกรรม, พืช", example: "The chemical plant is located away from residential zones." },
        { word: "Shift", read: "ชิฟต์", pos: "n.", meaning: "กะการทำงาน", example: "He prefers working the night shift because it is quiet." },
        { word: "Worker", read: "เวิร์ก-เกอร์", pos: "n.", meaning: "คนงาน", example: "Construction workers must wear hard hats at all times." },
        { word: "Safety", read: "เซฟ-ที", pos: "n.", meaning: "ความปลอดภัย", example: "Safety goggles protect your eyes from flying sparks." },
        { word: "Maintenance", read: "เมน-เท-แนนส์", pos: "n.", meaning: "การบำรุงรักษา", example: "Regular maintenance keeps machines running smoothly." },
        { word: "Manufacture", read: "แม-นิว-แฟค-เจอร์", pos: "v.", meaning: "ผลิตด้วยเครื่องจักรจำนวนมาก", example: "They manufacture pharmaceutical drugs under strict licenses." },
        { word: "Product", read: "พรอ-ดักต์", pos: "n.", meaning: "ผลิตภัณฑ์", example: "This liquid cleaner is our top-selling product." },
        { word: "Batch", read: "แบตช์", pos: "n.", meaning: "ชุดสินค้า, กลุ่มผลิตภัณฑ์", example: "The bakery makes a fresh batch of cookies every morning." },
        { word: "Blueprint", read: "บลู-ปริ้นท์", pos: "n.", meaning: "พิมพ์เขียว, แผนผังโครงสร้าง", example: "The architect explained the building blueprint to builders." },
        { word: "Specification", read: "สเป-ซิ-ฟิ-เค-ชัน", pos: "n.", meaning: "คุณลักษณะเฉพาะ", example: "The computer's technical specifications are listed online." },
        { word: "Efficient", read: "อิ-ฟิ-เชียนท์", pos: "adj.", meaning: "ที่มีประสิทธิภาพ", example: "LED bulbs are much more energy-efficient than older lights." },
        { word: "Overhaul", read: "โอ-เวอร์-ฮอล", pos: "v./n.", meaning: "การยกเครื่องตรวจสอบใหม่หมด", example: "Mechanics had to overhaul the entire aircraft engine." },
        { word: "Hazard", read: "แฮ-ซาร์ด", pos: "n.", meaning: "อันตราย, สิ่งที่เป็นภัย", example: "Spilled oil on the factory floor is a slip hazard." },
        { word: "Operator", read: "ออป-เปอ-เร-เทอร์", pos: "n.", meaning: "ผู้ควบคุมเครื่องจักร, พนักงานรับสาย", example: "The forklift operator loaded pallets into the container." },
        { word: "Calibrate", read: "แค-ลิ-เบรท", pos: "v.", meaning: "ปรับค่ามาตรฐานเครื่องมือ", example: "Technicians calibrate the scales to ensure exact weight." },
        { word: "Shortage", read: "ชอร์ต-ทิจ", pos: "n.", meaning: "การขาดแคลน", example: "Drought caused a severe water shortage in the province." },
        { word: "Wastage", read: "เวส-ทิจ", pos: "n.", meaning: "การสูญเสียโดยเปล่าประโยชน์", example: "Recycling metal scrap minimizes raw material wastage." },
        { word: "Superintendent", read: "ซู-ปรี-เทน-เดนท์", pos: "n.", meaning: "ผู้จัดการโรงงาน/ผู้ควบคุมดูแล", example: "The plant superintendent reviews daily productivity reports." }
    ],

    // === ชุดที่ 8: Travel & Transport ===
    set8: [
        { word: "Itinerary", read: "ไอ-ทิน-เนอ-แร-รี", pos: "n.", meaning: "แผนการเดินทาง", example: "The travel agent printed out our detailed holiday itinerary." },
        { word: "Flight", read: "ไฟลท์", pos: "n.", meaning: "เที่ยวบิน", example: "Our flight to London departs from terminal three." },
        { word: "Booking", read: "บุ๊ก-กิ้ง", pos: "n.", meaning: "การจอง", example: "I made an online booking for a rental car." },
        { word: "Reservation", read: "เร-เซอร์-เว-ชัน", pos: "n.", meaning: "การสำรองที่นั่ง/ห้องพัก", example: "We have a dinner reservation for 7:30 PM." },
        { word: "Passenger", read: "แพส-เซน-เจอร์", pos: "n.", meaning: "ผู้โดยสาร", example: "The train was crowded with commuters and passengers." },
        { word: "Luggage", read: "ลัก-เกจ", pos: "n.", meaning: "กระเป๋าเดินทาง", example: "Heavy luggage can be checked in at the airline counter." },
        { word: "Baggage", read: "แบ็ก-เกจ", pos: "n.", meaning: "สัมภาระ", example: "Please collect your baggage at carousel number five." },
        { word: "Ticket", read: "ทิก-เก็ต", pos: "n.", meaning: "ตั๋ว", example: "You must validate your train ticket before boarding." },
        { word: "Destination", read: "เดส-ติ-เน-ชัน", pos: "n.", meaning: "จุดหมายปลายทาง", example: "Paris is a popular tourist destination in Europe." },
        { word: "Depart", read: "ดิ-พาร์ต",pos: "v.", meaning: "ออกเดินทาง", example: "The tour bus will depart promptly at eight o'clock." },
        { word: "Arrive", read: "อะ-ไรฝ", pos: "v.", meaning: "มาถึง", example: "The package is expected to arrive tomorrow morning." },
        { word: "Boarding", read: "บอร์ด-ดิ้ง", pos: "n./adj.", meaning: "การขึ้นยานพาหนะ", example: "Boarding will begin twenty minutes before departure." },
        { word: "Accommodation", read: "อะ-คอม-โม-เด-ชัน", pos: "n.", meaning: "ที่พักแรม", example: "The hotel offers excellent luxury accommodation." },
        { word: "Shuttle", read: "ชัท-เทิล", pos: "n./v.", meaning: "รถรับส่งวิ่งระยะสั้น", example: "A complimentary shuttle bus runs between the airport and hotel." },
        { word: "Route", read: "รูท", pos: "n.", meaning: "เส้นทาง", example: "The GPS calculated the fastest route to the stadium." },
        { word: "Vehicle", read: "วี-ฮิ-เคิล", pos: "n.", meaning: "ยานพาหนะ", example: "Electric vehicles help reduce carbon emissions." },
        { word: "Commute", read: "คอม-มิวท์", pos: "v./n.", meaning: "เดินทางไปกลับที่ทำงานประจำ", example: "He commutes to the city office by train every day." },
        { word: "Fare", read: "แฟร์", pos: "n.", meaning: "ค่าโดยสาร", example: "Taxi fares increased slightly due to rising fuel costs." },
        { word: "Cruise", read: "ครูซ", pos: "n./v.", meaning: "การล่องเรือสำราญ", example: "They went on a Mediterranean cruise for their anniversary." },
        { word: "Journey", read: "เจอร์-นี", pos: "n.", meaning: "การเดินทางไกล", example: "The train journey through Switzerland was breathtaking." },
        { word: "Agency", read: "เอ-เจน-ซี", pos: "n.", meaning: "ตัวแทนผู้ให้บริการ", example: "We hired a rental agency to find an office space." },
        { word: "Terminal", read: "เทอร์-มิ-นอล", pos: "n.", meaning: "สถานีปลายทาง, อาคารผู้โดยสาร", example: "Passengers walked to terminal two for domestic flights." },
        { word: "Expressway", read: "เอ็กซ์-เพรส-เวย์", pos: "n.", meaning: "ทางด่วน", example: "Using the expressway cuts driving time in half." },
        { word: "Passport", read: "พาส-พอร์ต", pos: "n.", meaning: "หนังสือเดินทาง", example: "Make sure your passport is valid for at least six months." },
        { word: "Visa", read: "วี-ซ่า", pos: "n.", meaning: "วีซ่าเอกสารเข้าเมือง", example: "Tourists from certain countries require a visa to enter." },
        { word: "Delayed", read: "ดิ-เลย์ด", pos: "adj.", meaning: "ที่ล่าช้าออกไป", example: "The delayed flight finally took off three hours later." },
        { word: "Customs", read: "คัส-ตัมส์", pos: "n.", meaning: "ศุลกากรกรองสินค้า", example: "All international purchases must clear customs checks." },
        { word: "Refundable", read: "รี-ฟัน-ดะ-เบิล", pos: "adj.", meaning: "สามารถขอเงินคืนได้", example: "The economy flight ticket is non-refundable." },
        { word: "Boutique", read: "บู-ทีค", pos: "adj./n.", meaning: "ขนาดเล็กที่ตกแต่งมีสไตล์", example: "We stayed at a charming boutique hotel near the beach." },
        { word: "Check-in", read: "เช็ค-อิน", pos: "n./v.", meaning: "ลงทะเบียนเข้าพัก/ขึ้นเครื่อง", example: "The check-in counter closes forty minutes before the flight." }
    ],

    // === ชุดที่ 9: Hospitality & Catering ===
    set9: [
        { word: "Hotel", read: "โฮ-เทล", pos: "n.", meaning: "โรงแรม", example: "The five-star hotel features an infinity outdoor pool." },
        { word: "Menu", read: "เม-นู", pos: "n.", meaning: "รายการอาหาร", example: "The restaurant menu includes several vegetarian dishes." },
        { word: "Recipe", read: "เร-ซิ-พี", pos: "n.", meaning: "สูตรอาหาร", example: "My grandmother shared her secret chocolate cake recipe." },
        { word: "Chef", read: "เชฟ", pos: "n.", meaning: "หัวหน้าพ่อครัว", example: "The head chef prepared a special tasting menu tonight." },
        { word: "Server", read: "เซิร์ฟ-เวอร์", pos: "n.", meaning: "พนักงานบริการ, เซิร์ฟเวอร์คอมพิวเตอร์", example: "The server recommended the grilled salmon dish." },
        { word: "Customer", read: "คัส-ตอม-เมอร์", pos: "n.", meaning: "ลูกค้า", example: "A satisfied customer is likely to return to the shop." },
        { word: "Guest", read: "เกสต์", pos: "n.", meaning: "แขกผู้มาเยือน", example: "Hotel guests can enjoy free Wi-Fi in all rooms." },
        { word: "Buffet", read: "บุฟ-เฟต์", pos: "n.", meaning: "อาหารแบบบุฟเฟต์บริการตนเอง", example: "The hotel serves a complimentary breakfast buffet." },
        { word: "Beverage", read: "เบฝ-เวอ-เรจ", pos: "n.", meaning: "เครื่องดื่ม", example: "Alcoholic beverages are not served to anyone under twenty." },
        { word: "Cuisine", read: "ควิ-ซีน", pos: "n.", meaning: "ประเภทหรือสไตล์อาหาร", example: "Italian cuisine is famous for pasta and pizza worldwide." },
        { word: "Service", read: "เซอร์-วิส", pos: "n./v.", meaning: "การบริการ", example: "The food was delicious and the service was excellent." },
        { word: "Housekeeping", read: "เฮาส์-คีป-ปิ้ง", pos: "n.", meaning: "แผนกแม่บ้านทำความสะอาด", example: "Call housekeeping if you need fresh towels in your room." },
        { word: "Amenity", read: "อะ-เมน-นิ-ที", pos: "n.", meaning: "สิ่งอำนวยความสะดวก", example: "The resort offers upscale amenities like a private spa." },
        { word: "Check-out", read: "เช็ค-เอาต์", pos: "n./v.", meaning: "การคืนห้องพักและเช็คบิล", example: "Hotel check-out time is strictly at twelve noon." },
        { word: "Lobby", read: "ลอบ-บี", pos: "n.", meaning: "โถงรับรองส่วนหน้า", example: "We arranged to meet our client in the main lobby." },
        { word: "Front Desk", read: "ฟรอนท์ เดสก์", pos: "n.", meaning: "โต๊ะประชาสัมพันธ์ส่วนหน้า", example: "You can collect your room key card at the front desk." },
        { word: "Banquet", read: "แบง-ควิท", pos: "n.", meaning: "งานจัดเลี้ยงขนาดใหญ่", example: "The wedding banquet was held in the grand ballroom." },
        { word: "Dessert", read: "ดิ-เซิร์ท", pos: "n.", meaning: "ของหวาน", example: "Apple pie with ice cream is a classic dessert." },
        { word: "Ingredient", read: "อิน-กรี-เดียนท์", pos: "n.", meaning: "ส่วนผสมอาหาร", example: "Fresh basil is a key ingredient in this green pesto." },
        { word: "Cater", read: "เค-เทอร์", pos: "v.", meaning: "จัดเลี้ยงอาหาร, บริการความต้องการ", example: "They hired a famous company to cater the corporate dinner." },
        { word: "Lounge", read: "เลานจ์", pos: "n.", meaning: "ห้องนั่งเล่นพักผ่อน", example: "Business class passengers have access to the airport lounge." },
        { word: "Refreshment", read: "รี-เฟรช-เม้นท์", pos: "n.", meaning: "เครื่องดื่มและของว่างเบาๆ", example: "Light refreshments were served after the presentation." },
        { word: "Review", read: "รี-วิว", pos: "n./v.", meaning: "การวิจารณ์, ตรวจสอบ", example: "The restaurant received a five-star review online." },
        { word: "Compliment", read: "คอม-พลี-เม้นท์", pos: "n./v.", meaning: "คำชมเชย", example: "The guest paid a warm compliment to the pastry chef." },
        { word: "Complaint", read: "คอม-เพลนท์", pos: "n.", meaning: "ข้อร้องเรียน", example: "The customer filed a complaint about the cold soup." },
        { word: "Tip", read: "ทิป", pos: "n./v.", meaning: "เงินรางวัลพิเศษ, เคล็ดลับ", example: "It is customary to leave a fifteen percent tip for waiters." },
        { word: "Hospitality", read: "ฮอส-พิ-แทล-ลิ-ที", pos: "n.", meaning: "การต้อนรับขับสู้ด้วยมิตรไมตรี", example: "Thank you for your warm hospitality during our stay." },
        { word: "Reservation", read: "เร-เซอร์-เว-ชัน", pos: "n.", meaning: "การจองล่วงหน้า", example: "The popular bistro does not accept weekend reservations." },
        { word: "Gourmet", read: "กูร์-เมต์", pos: "adj./n.", meaning: "อาหารเลิศรส", example: "He bought artisanal cheese at the gourmet grocery market." },
        { word: "Platter", read: "แพลต-เทอร์", pos: "n.", meaning: "จานเปลขนาดใหญ่ที่เสิร์ฟอาหารรวม", example: "We shared a large platter of fresh Mediterranean seafood." }
    ],

    // === ชุดที่ 10: Health & Technology ===
    set10: [
        { word: "Software", read: "ซอฟต์-แวร์", pos: "n.", meaning: "โปรแกรมคอมพิวเตอร์", example: "Our company installs antivirus software on every computer." },
        { word: "Hardware", read: "ฮาร์ด-แวร์", pos: "n.", meaning: "อุปกรณ์คอมพิวเตอร์ที่เป็นวัตถุ", example: "The tech team is upgrading the office server hardware." },
        { word: "Network", read: "เน็ต-เวิร์ก", pos: "n./v.", meaning: "เครือข่ายสัญญาณ", example: "A poor network connection slowed down the file download." },
        { word: "Database", read: "เด-ตา-เบส", pos: "n.", meaning: "ฐานข้อมูล", example: "Customer contact info is saved in a secure database." },
        { word: "Device", read: "ดิ-ไวซ์", pos: "n.", meaning: "อุปกรณ์, เครื่องมือ", example: "Smartphones are essential electronic devices nowadays." },
        { word: "System", read: "ซิส-เท็ม", pos: "n.", meaning: "ระบบ", example: "The building's air conditioning system is fully automatic." },
        { word: "Update", read: "อัป-เดท", pos: "v./n.", meaning: "อัปเดตข้อมูลล่าสุด", example: "Please update your phone's operating system regularly." },
        { word: "Upgrade", read: "อัป-เกรด", pos: "v./n.", meaning: "ยกระดับคุณภาพให้ดีขึ้น", example: "I decided to upgrade my laptop's random access memory." },
        { word: "Security", read: "ซิ-คิว-ริ-ที", pos: "n.", meaning: "ความปลอดภัย", example: "Cyber security protects private data from global hackers." },
        { word: "Virus", read: "ไว-รัส", pos: "n.", meaning: "เชื้อไวรัสโรค, ไวรัสคอมพิวเตอร์", example: "A computer virus deleted all the files on his drive." },
        { word: "Backup", read: "แบ็ก-อัป", pos: "n./v.", meaning: "การสำรองข้อมูลไว้กันหาย", example: "Always create a regular backup of important work documents." },
        { word: "Install", read: "อิน-สทอล", pos: "v.", meaning: "ติดตั้งโปรแกรมหรืออุปกรณ์", example: "The IT technician will install the new office software." },
        { word: "Program", read: "โปร-แกรม", pos: "n./v.", meaning: "ชุดคำสั่งรันระบบ, รายการ", example: "He learned to program in Python at a young age." },
        { word: "Technical", read: "เทค-นิ-คอล", pos: "adj.", meaning: "ทางเทคนิค, เชี่ยวชาญเฉพาะ", example: "Call technical support if you face glitches." },
        { word: "Support", read: "ซัพ-พอร์ต", pos: "v./n.", meaning: "การสนับสนุนช่วยเหลือ", example: "Our customer support helpline is available 24/7." },
        { word: "Clinic", read: "คลิ-นิก", pos: "n.", meaning: "คลินิกสถานพยาบาล", example: "He visited a dental clinic to get his teeth cleaned." },
        { word: "Patient", read: "เพ-เชียนท์", pos: "n./adj.", meaning: "คนไข้, ที่มีความอดทน", example: "The doctor spent thirty minutes with each patient." },
        { word: "Doctor", read: "ด็อก-เทอร์", pos: "n.", meaning: "แพทย์", example: "The doctor prescribed rest for his severe headache." },
        { word: "Medicine", read: "เมด-ดิ-ซิน", pos: "n.", meaning: "ยารักษาโรค, แพทยศาสตร์", example: "Take this medicine twice a day after meals." },
        { word: "Treatment", read: "ทรีต-เม้นท์", pos: "n.", meaning: "การรักษา, การปฏิบัติเชิดชู", example: "Physical therapy is an effective treatment for back pain." },
        { word: "Symptom", read: "ซิม-ทอม", pos: "n.", meaning: "อาการของโรค", example: "Fever and a sore throat are common cold symptoms." },
        { word: "Prescription", read: "พรี-สคริป-ชัน", pos: "n.", meaning: "ใบสั่งยาจากแพทย์", example: "You need a valid prescription to buy these antibiotics." },
        { word: "Checkup", read: "เช็ค-อัป", pos: "n.", meaning: "การตรวจสุขภาพร่างกายประจำปี", example: "An annual medical checkup helps detect health risks early." },
        { word: "Fitness", read: "ฟิต-เนส", pos: "n.", meaning: "ความแข็งแรงของร่างกาย, สถานออกกำลังกาย", example: "Regular exercise improves your cardiovascular fitness." },
        { word: "Diagnosis", read: "ได-แอก-โน-ซิส", pos: "n.", meaning: "การวินิจฉัยโรค", example: "The doctor made an accurate diagnosis after checking test results." },
        { word: "Healthy", read: "เฮล-ธี", pos: "adj.", meaning: "ที่มีสุขภาพดี", example: "Eating green fresh vegetables keeps your body healthy." },
        { word: "Laboratory", read: "แล็บ-บอ-รา-ทอ-รี", pos: "n.", meaning: "ห้องปฏิบัติการทดลอง", example: "Blood samples were sent to the laboratory for analysis." },
        { word: "Prevent", read: "พริ-เวนท์", pos: "v.", meaning: "ป้องกันไม่ให้เกิด", example: "Wearing face masks helps prevent the spread of virus germs." },
        { word: "Recovery", read: "รี-คัฝ-เวอ-รี", pos: "n.", meaning: "การฟื้นตัว, การกู้คืนข้อมูล", example: "We wish you a very speedy recovery from surgery." },
        { word: "Cyber", read: "ไซ-เบอร์", pos: "adj.", meaning: "เกี่ยวกับเครือข่ายคอมพิวเตอร์", example: "The government introduced new cyber crime protection laws." }
    ]
};