// ฐานข้อมูลคำศัพท์ TOEIC 10 ชุด ชุดละ 30 คำ (รวม 300 คำ)
const vocabSets = {
    set1: [ // Marketing & Sales
        { word: "Advertise", meaning: "โฆษณา" }, { word: "Brand", meaning: "ตราสินค้า" },
        { word: "Campaign", meaning: "แคมเปญ, การรณรงค์" }, { word: "Consumer", meaning: "ผู้บริโภค" },
        { word: "Demand", meaning: "ความต้องการ" }, { word: "Promote", meaning: "ส่งเสริม, เลื่อนตำแหน่ง" },
        { word: "Strategy", meaning: "กลยุทธ์" }, { word: "Target", meaning: "เป้าหมาย" },
        { word: "Trend", meaning: "แนวโน้ม" }, { word: "Sponsor", meaning: "ผู้สนับสนุน" },
        { word: "Brochure", meaning: "แผ่นพับ" }, { word: "Publicity", meaning: "การประชาสัมพันธ์" },
        { word: "Survey", meaning: "การสำรวจ" }, { word: "Feedback", meaning: "ผลตอบรับ" },
        { word: "Launch", meaning: "เปิดตัวสินค้า" }, { word: "Logo", meaning: "สัญลักษณ์" },
        { word: "Slogan", meaning: "สโลแกน" }, { word: "Competitor", meaning: "คู่แข่ง" },
        { word: "Market Share", meaning: "ส่วนแบ่งการตลาด" }, { word: "Niche", meaning: "กลุ่มตลาดเฉพาะ" },
        { word: "Segment", meaning: "ส่วนตลาด" }, { word: "Loyalty", meaning: "ความจงรักภักดี" },
        { word: "Endorse", meaning: "รับรอง, เป็นพรีเซนเตอร์" }, { word: "Merchandise", meaning: "สินค้า" },
        { word: "Retail", meaning: "การขายปลีก" }, { word: "Wholesale", meaning: "การขายส่ง" },
        { word: "Discount", meaning: "ส่วนลด" }, { word: "Attraction", meaning: "การดึงดูด" },
        { word: "Display", meaning: "การจัดแสดง" }, { word: "Persuade", meaning: "โน้มน้าว" }
    ],
    set2: [ // Finance & Accounting
        { word: "Revenue", meaning: "รายได้" }, { word: "Budget", meaning: "งบประมาณ" },
        { word: "Expense", meaning: "ค่าใช้จ่าย" }, { word: "Profit", meaning: "กำไร" },
        { word: "Loss", meaning: "การขาดทุน" }, { word: "Audit", meaning: "ตรวจสอบบัญชี" },
        { word: "Balance", meaning: "ยอดคงเหลือ" }, { word: "Currency", meaning: "สกุลเงิน" },
        { word: "Debt", meaning: "หนี้สิน" }, { word: "Deficit", meaning: "การขาดดุล" },
        { word: "Finance", meaning: "การเงิน" }, { word: "Insurance", meaning: "การประกันภัย" },
        { word: "Investment", meaning: "การลงทุน" }, { word: "Loan", meaning: "เงินกู้" },
        { word: "Transaction", meaning: "ธุรกรรม" }, { word: "Asset", meaning: "สินทรัพย์" },
        { word: "Liability", meaning: "หนี้สินตามกฎหมาย" }, { word: "Capital", meaning: "เงินทุน" },
        { word: "Dividend", meaning: "เงินปันผล" }, { word: "Bankruptcy", meaning: "การล้มละลาย" },
        { word: "Inflation", meaning: "เงินเฟ้อ" }, { word: "Interest Rate", meaning: "อัตราดอกเบี้ย" },
        { word: "Mortgage", meaning: "การจำนอง" }, { word: "Receipt", meaning: "ใบเสร็จ" },
        { word: "Invoice", meaning: "ใบแจ้งหนี้" }, { word: "Refund", meaning: "การคืนเงิน" },
        { word: "Tax", meaning: "ภาษี" }, { word: "Portfolio", meaning: "หลักทรัพย์ในครอบครอง" },
        { word: "Stocks", meaning: "หุ้น" }, { word: "Withdraw", meaning: "ถอนเงิน" }
    ],
    set3: [ // Corporate Management
        { word: "Executive", meaning: "ผู้บริหาร" }, { word: "Acquisition", meaning: "การซื้อกิจการ" },
        { word: "Merge", meaning: "ควบรวมกิจการ" }, { word: "Subsidiary", meaning: "บริษัทในเครือ" },
        { word: "Shareholder", meaning: "ผู้ถือหุ้น" }, { word: "Stakeholder", meaning: "ผู้มีส่วนได้ส่วนเสีย" },
        { word: "Enterprise", meaning: "บริษัท, กิจการ" }, { word: "Board of Directors", meaning: "คณะกรรมการบริหาร" },
        { word: "Restructure", meaning: "ปรับโครงสร้าง" }, { word: "Compliance", meaning: "การปฏิบัติตามกฎ" },
        { word: "Regulation", meaning: "กฎข้อบังคับ" }, { word: "Policy", meaning: "นโยบาย" },
        { word: "Vision", meaning: "วิสัยทัศน์" }, { word: "Mission", meaning: "พันธกิจ" },
        { word: "Affiliate", meaning: "บริษัทในเครือ" }, { word: "Monopoly", meaning: "การผูกขาด" },
        { word: "Conglomerate", meaning: "กลุ่มบริษัทในเครือข่าย" }, { word: "Venture", meaning: "การเสี่ยงลงทุน" },
        { word: "Expansion", meaning: "การขยายตัว" }, { word: "Supervision", meaning: "การควบคุมดูแล" },
        { word: "Consultant", meaning: "ที่ปรึกษา" }, { word: "Representative", meaning: "ตัวแทน" },
        { word: "Branch", meaning: "สาขา" }, { word: "Headquarters", meaning: "สำนักงานใหญ่" },
        { word: "Partnership", meaning: "หุ้นส่วน" }, { word: "Cooperation", meaning: "การร่วมมือ" },
        { word: "Leadership", meaning: "ความเป็นผู้นำ" }, { word: "Objective", meaning: "วัตถุประสงค์" },
        { word: "Procedure", meaning: "ขั้นตอนการทำงาน" }, { word: "Guidelines", meaning: "แนวทางปฏิบัติ" }
    ],
    set4: [ // Human Resources
        { word: "Candidate", meaning: "ผู้สมัคร" }, { word: "Recruit", meaning: "รับสมัครงาน" },
        { word: "Applicant", meaning: "ผู้สมัครงาน" }, { word: "Resume", meaning: "ประวัติส่วนตัว" },
        { word: "Interview", meaning: "การสัมภาษณ์" }, { word: "Benefit", meaning: "สวัสดิการ" },
        { word: "Compensation", meaning: "ค่าตอบแทน" }, { word: "Retire", meaning: "เกษียณอายุ" },
        { word: "Resign", meaning: "ลาออก" }, { word: "Terminate", meaning: "เลิกจ้าง" },
        { word: "Promote", meaning: "เลื่อนตำแหน่ง" }, { word: "Evaluate", meaning: "ประเมินผล" },
        { word: "Performance", meaning: "ผลการปฏิบัติงาน" }, { word: "Qualification", meaning: "คุณสมบัติ" },
        { word: "Apprentice", meaning: "เด็กฝึกงาน" }, { word: "Vacancy", meaning: "ตำแหน่งว่าง" },
        { word: "Overtime", meaning: "การทำงานล่วงเวลา" }, { word: "Payroll", meaning: "บัญชีเงินเดือน" },
        { word: "Salary", meaning: "เงินเดือน" }, { word: "Wage", meaning: "ค่าจ้าง" },
        { word: "Allowance", meaning: "เบี้ยเลี้ยง" }, { word: "Bonus", meaning: "เงินโบนัส" },
        { word: "Probation", meaning: "การทดลองงาน" }, { word: "Criteria", meaning: "เกณฑ์การตัดสิน" },
        { word: "Competence", meaning: "ความรู้ความสามารถ" }, { word: "Expertise", meaning: "ความเชี่ยวชาญ" },
        { word: "Background", meaning: "ภูมิหลัง, ประวัติ" }, { word: "References", meaning: "บุคคลอ้างอิง" },
        { word: "Pension", meaning: "เงินบำนาญ" }, { word: "Labor", meaning: "แรงงาน" }
    ],
    set5: [ // Office Administration
        { word: "Agenda", meaning: "ระเบียบวาระการประชุม" }, { word: "Minutes", meaning: "รายงานการประชุม" },
        { word: "Memo", meaning: "บันทึกข้อความ" }, { word: "Colleague", meaning: "เพื่อนร่วมงาน" },
        { word: "Supervisor", meaning: "ผู้ดูแล, หัวหน้างาน" }, { word: "Subordinate", meaning: "ผู้ใต้บังคับบัญชา" },
        { word: "Schedule", meaning: "กำหนดการ" }, { word: "Postpone", meaning: "เลื่อนเวลาออกไป" },
        { word: "Cancel", meaning: "ยกเลิก" }, { word: "Confirm", meaning: "ยืนยัน" },
        { word: "Coordinate", meaning: "ประสานงาน" }, { word: "Delegate", meaning: "มอบหมายงาน" },
        { word: "Organize", meaning: "จัดระเบียบ" }, { word: "Archive", meaning: "คลังเอกสารเก่า" },
        { word: "Document", meaning: "เอกสาร" }, { word: "Efficient", meaning: "มีประสิทธิภาพ" },
        { word: "Productive", meaning: "ได้ผลผลิตสูง" }, { word: "Deadline", meaning: "กำหนดส่งงาน" },
        { word: "Extension", meaning: "การขยายเวลา, สายต่อ" }, { word: "Urgent", meaning: "เร่งด่วน" },
        { word: "Routine", meaning: "งานประจำ" }, { word: "Equipment", meaning: "อุปกรณ์" },
        { word: "Inventory", meaning: "สินค้าคงคลัง" }, { word: "Supply", meaning: "วัสดุอุปกรณ์, เสบียง" },
        { word: "Maintenance", meaning: "การบำรุงรักษา" }, { word: "Stationery", meaning: "เครื่องเขียน" },
        { word: "Facility", meaning: "สิ่งอำนวยความสะดวก" }, { word: "Cabinet", meaning: "ตู้เก็บเอกสาร" },
        { word: "Workspace", meaning: "พื้นที่ทำงาน" }, { word: "Correspondence", meaning: "การติดต่อทางจดหมาย" }
    ],
    set6: [ // Purchasing & Logistics
        { word: "Affordable", meaning: "ราคาไม่แพง, จ่ายได้" }, { word: "Negotiate", meaning: "เจรจาต่อรอง" },
        { word: "Vendor", meaning: "ผู้ขาย, ผู้จำหน่าย" }, { word: "Supplier", meaning: "ผู้จัดหาสินค้า" },
        { word: "Purchase", meaning: "ซื้อ" }, { word: "Order", meaning: "สั่งซื้อ" },
        { word: "Delivery", meaning: "การจัดส่ง" }, { word: "Shipment", meaning: "การขนส่งสินค้า" },
        { word: "Cargo", meaning: "สินค้าที่บรรทุกคันรถ/เรือ" }, { word: "Freight", meaning: "ค่าขนส่ง, สินค้าขนส่ง" },
        { word: "Warehouse", meaning: "คลังสินค้า" }, { word: "Logistics", meaning: "ระบบการขนส่ง" },
        { word: "Carrier", meaning: "บริษัทขนส่ง" }, { word: "Dispatch", meaning: "ส่งของ, ออกเดินทาง" },
        { word: "Wharf", meaning: "ท่าเรือ" }, { word: "Customs", meaning: "ศุลกากร" },
        { word: "Tariff", meaning: "ภาษีศุลกากร" }, { word: "Quotation", meaning: "ใบเสนอราคา" },
        { word: "Contract", meaning: "สัญญา" }, { word: "Agreement", meaning: "ข้อตกลง" },
        { word: "Wholesaler", meaning: "พ่อค้าส่ง" }, { word: "Distributor", meaning: "ผู้จัดจำหน่าย" },
        { word: "Procurement", meaning: "การจัดซื้อจัดจ้าง" }, { word: "Consignment", meaning: "การฝากขาย" },
        { word: "Tracking", meaning: "การติดตามสถานะ" }, { word: "Receipt", meaning: "การได้รับ, ใบเสร็จ" },
        { word: "Transit", meaning: "การเดินทางผ่าน" }, { word: "Insurance", meaning: "การประกันภัย" },
        { word: "Bulk", meaning: "ปริมาณมาก" }, { word: "Defective", meaning: "มีตำหนิ, ชำรุด" }
    ],
    set7: [ // Manufacturing & Quality Control
        { word: "Assemble", meaning: "ประกอบชิ้นส่วน" }, { word: "Factory", meaning: "โรงงาน" },
        { word: "Manufacture", meaning: "ผลิตด้วยเครื่องจักร" }, { word: "Component", meaning: "ส่วนประกอบ" },
        { word: "Defect", meaning: "ข้อบกพร่อง" }, { word: "Inspect", meaning: "ตรวจสอบ" },
        { word: "Machinery", meaning: "เครื่องจักร" }, { word: "Output", meaning: "ผลผลิต" },
        { word: "Plant", meaning: "โรงงาน, โรงไฟฟ้า" }, { word: "Raw Material", meaning: "วัตถุดิบ" },
        { word: "Standard", meaning: "มาตรฐาน" }, { word: "Automate", meaning: "ทำให้เป็นอัตโนมัติ" },
        { word: "Batch", meaning: "ชุดการผลิต" }, { word: "Capacity", meaning: "ความจุ, กำลังการผลิต" },
        { word: "Laborer", meaning: "กรรมกร" }, { word: "Maintenance", meaning: "การบำรุงรักษา" },
        { word: "Operation", meaning: "การปฏิบัติการ" }, { word: "Operator", meaning: "ผู้ควบคุมเครื่องจักร" },
        { word: "Pipeline", meaning: "แนวท่อส่ง" }, { word: "Procedure", meaning: "ขั้นตอน" },
        { word: "Productivity", meaning: "ความสามารถในการผลิต" }, { word: "Quality Assurance", meaning: "การประกันคุณภาพ" },
        { word: "Safety", meaning: "ความปลอดภัย" }, { word: "Shift", meaning: "กะการทำงาน" },
        { word: "Shortage", meaning: "การขาดแคลน" }, { word: "Specification", meaning: "คุณลักษณะเฉพาะ" },
        { word: "Surplus", meaning: "ส่วนเกิน" }, { word: "Technician", meaning: "ช่างเทคนิค" },
        { word: "Warehouse", meaning: "โกดัง" }, { word: "Yield", meaning: "ผลผลิต, ยอมแพ้" }
    ],
    set8: [ // Travel & Transportation
        { word: "Accommodation", meaning: "ที่พัก" }, { word: "Itinerary", meaning: "แผนการเดินทาง" },
        { word: "Luggage", meaning: "กระเป๋าเดินทาง" }, { word: "Baggage", meaning: "กระเป๋าเดินทาง" },
        { word: "Delay", meaning: "ความล่าช้า" }, { word: "Departure", meaning: "การขาออก" },
        { word: "Arrival", meaning: "การขาเข้า" }, { word: "Destination", meaning: "จุดหมายปลายทาง" },
        { word: "Fare", meaning: "ค่าโดยสาร" }, { word: "Reservation", meaning: "การจอง" },
        { word: "Boarding Pass", meaning: "บัตรขึ้นเครื่อง" }, { word: "Cancel", meaning: "ยกเลิก" },
        { word: "Confirm", meaning: "ยืนยัน" }, { word: "Cruise", meaning: "การล่องเรือสำราญ" },
        { word: "Expedition", meaning: "การเดินทางสำรวจ" }, { word: "Flight", meaning: "เที่ยวบิน" },
        { word: "Journey", meaning: "การเดินทาง" }, { word: "Passenger", meaning: "ผู้โดยสาร" },
        { word: "Route", meaning: "เส้นทาง" }, { word: "Shuttle", meaning: "รถรับส่ง" },
        { word: "Terminal", meaning: "อาคารผู้โดยสาร" }, { word: "Ticket", meaning: "ตั๋ว" },
        { word: "Transit", meaning: "การเปลี่ยนเครื่อง" }, { word: "Transport", meaning: "การขนส่ง" },
        { word: "Vacancy", meaning: "ห้องว่าง" }, { word: "Vehicle", meaning: "ยานพาหนะ" },
        { word: "Via", meaning: "ผ่านทาง" }, { word: "Visa", meaning: "วีซ่า" },
        { word: "Voyage", meaning: "การเดินทางทางเรือ" }, { word: "Check-in", meaning: "ลงทะเบียนเข้าพัก" }
    ],
    set9: [ // Hospitality & Catering
        { word: "Amenity", meaning: "สิ่งอำนวยความสะดวก" }, { word: "Appetizer", meaning: "อาหารเรียกน้ำย่อย" },
        { word: "Beverage", meaning: "เครื่องดื่ม" }, { word: "Buffet", meaning: "บุฟเฟต์" },
        { word: "Catering", meaning: "การจัดเลี้ยง" }, { word: "Chef", meaning: "หัวหน้าพ่อครัว" },
        { word: "Complimentary", meaning: "ให้ฟรี, เพื่อเป็นการชมเชย" }, { word: "Concierge", meaning: "พนักงานต้อนรับส่วนหน้า" },
        { word: "Cuisine", meaning: "ประเภทอาหาร" }, { word: "Dessert", meaning: "ของหวาน" },
        { word: "Dietary", meaning: "เกี่ยวกับอาหาร" }, { word: "Entree", meaning: "อาหารจานหลัก" },
        { word: "Gourmet", meaning: "นักชิมอาหาร, อาหารรสเลิศ" }, { word: "Hospitality", meaning: "การต้อนรับขับสู้" },
        { word: "Ingredient", meaning: "ส่วนผสม" }, { word: "Lounge", meaning: "ห้องนั่งเล่น" },
        { word: "Menu", meaning: "รายการอาหาร" }, { word: "Napkin", meaning: "ผ้าเช็ดปาก" },
        { word: "Platter", meaning: "จานเปลขนาดใหญ่" }, { word: "Refreshment", meaning: "เครื่องดื่มและอาหารว่าง" },
        { word: "Reservation", meaning: "การจอง" }, { word: "Recipe", meaning: "ตำราอาหาร" },
        { word: "Service", meaning: "การบริการ" }, { word: "Suite", meaning: "ห้องชุดในโรงแรม" },
        { word: "Tip", meaning: "เงินรางวัลพิเศษ" }, { word: "Utensil", meaning: "อุปกรณ์เครื่องใช้ในครัว" },
        { word: "Waiter", meaning: "บริกรชาย" }, { word: "Waitress", meaning: "บริกรหญิง" },
        { word: "Valet", meaning: "พนักงานนำรถไปจอด" }, { word: "Banquet", meaning: "งานเลี้ยง" }
    ],
    set10: [ // Health & Technology
        { word: "Innovation", meaning: "นวัตกรรม" }, { word: "Device", meaning: "อุปกรณ์" },
        { word: "Software", meaning: "ซอฟต์แวร์" }, { word: "Hardware", meaning: "ฮาร์ดแวร์" },
        { word: "Network", meaning: "เครือข่าย" }, { word: "Security", meaning: "ความปลอดภัย" },
        { word: "Database", meaning: "ฐานข้อมูล" }, { word: "System", meaning: "ระบบ" },
        { word: "Technical", meaning: "ทางเทคนิค" }, { word: "Upgrade", meaning: "ปรับปรุงระดับ" },
        { word: "Interface", meaning: "ส่วนต่อประสานผู้ใช้" }, { word: "Application", meaning: "แอปพลิเคชัน" },
        { word: "Backup", meaning: "การสำรองข้อมูล" }, { word: "Browse", meaning: "ท่องอินเทอร์เน็ต" },
        { word: "Data", meaning: "ข้อมูล" }, { word: "Clinic", meaning: "คลินิก" },
        { word: "Diagnosis", meaning: "การวินิจฉัยโรค" }, { word: "Examination", meaning: "การตรวจร่างกาย" },
        { word: "Health", meaning: "สุขภาพ" }, { word: "Insurance", meaning: "การประกันภัย" },
        { word: "Medical", meaning: "ทางการแพทย์" }, { word: "Medicine", meaning: "ยา" },
        { word: "Patient", meaning: "คนไข้" }, { word: "Physician", meaning: "แพทย์" },
        { word: "Prescription", meaning: "ใบสั่งยา" }, { word: "Treatment", meaning: "การรักษา" },
        { word: "Vaccine", meaning: "วัคซีน" }, { word: "Wellness", meaning: "ภาวะสุขภาพดี" },
        { word: "Appointment", meaning: "การนัดหมาย" }, { word: "Symptoms", meaning: "อาการของโรค" }
    ]
};